import{a as b,i as n,S as B}from"./assets/vendor-f144e563.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const g of s.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&a(g)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();const w=b.create({baseURL:"https://pixabay.com"});async function h(t,e,o){try{return(await w.get("/api/",{params:{key:"44578932-6e2bdfbc9295001d2a495ef0a",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:o,page:e}})).data}catch(a){n.error({title:"Error",message:`${a}`,layout:2,displayMode:"once",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",position:"topRight"})}}function y(t){const e=t.map(o=>`<li class="gallery-item">
        <a class="gallery-link" href="${o.largeImageURL}">
            <img
                width=360;
                height=200;
                class="gallery-image"
                src="${o.webformatURL}"
                alt="${o.tags} " />
        </a>
                <div class="image-info">
                <p class = "info-item"><strong>LIKES:</strong> ${o.likes}</p>
                <p class = "info-item"><strong>VIEWS:</strong> ${o.views}</p>
                <p class = "info-item"><strong>COMMENTS:</strong> ${o.comments}</p>
                <p class = "info-item"><strong>DOWNLOADS: </strong>${o.downloads}</p>
                </div>
        </li>
        `).join("");i.imgGallery.insertAdjacentHTML("beforeend",e)}function m(){i.formSearch.reset()}function l(){i.loader.classList.remove("hidden")}function L(){i.moreBtn.classList.remove("more-hidden")}function f(){i.moreBtn.classList.add("more-hidden")}function E(t,e){t<=e?L():(f(),n.info({title:"The end!",message:"We're sorry, but you've reached the end of search results."}))}function M(t=0,e=0){const a=i.imgGallery.children[0].getBoundingClientRect().height;window.scrollBy({top:a*2,left:e,behavior:"smooth"})}let d="",c=1,u=1;const p=15,i={formSearch:document.querySelector(".form"),inputImgSearch:document.querySelector(".input-search"),imgGallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),moreBtn:document.querySelector(".more-button")},S=new B(".gallery a",{captionsData:"alt",captionDelay:250});i.formSearch.addEventListener("submit",async t=>{if(t.preventDefault(),c=1,d=i.inputImgSearch.value.trim(),d===""){i.imgGallery.innerHTML=" ",n.warning({title:"warning",message:" Enter a word for the query, please.",layout:2,position:"topRight",displayMode:"once",color:"#ef4000",messageColor:"#fff",messageSize:"16"}),f(),m();return}l(),i.imgGallery.innerHTML=" ";try{const e=await h(d,c,p);if(u=Math.ceil(e.totalHits/p),u===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",displayMode:"once",color:"#ef4040",messageColor:"#fff",messageSize:"16",layout:2}),m(),l();return}m(),y(e.hits),l(),S.refresh(),L()}catch(e){n.error({title:"Error",message:`${e}`,layout:2,displayMode:"once",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",position:"topRight"})}});i.moreBtn.addEventListener("click",async()=>{try{l(),f(),c++;const t=await h(d,c,p);t.hits.length!==0&&(y(t.hits),S.refresh(),l()),M(),E(c,u)}catch(t){f(),n.error({title:"Error",message:`${t}`,layout:2,displayMode:"once",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",position:"topRight"})}});
//# sourceMappingURL=commonHelpers.js.map
