import{a as B,i as n,S as w}from"./assets/vendor-f144e563.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const i of r)if(i.type==="childList")for(const d of i.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function o(r){const i={};return r.integrity&&(i.integrity=r.integrity),r.referrerPolicy&&(i.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?i.credentials="include":r.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function a(r){if(r.ep)return;r.ep=!0;const i=o(r);fetch(r.href,i)}})();const E=B.create({baseURL:"https://pixabay.com"});async function h(t,e,o){try{return(await E.get("/api/",{params:{key:"44578932-6e2bdfbc9295001d2a495ef0a",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:o,page:e}})).data}catch(a){n.error({title:"Error",message:`${a}`,layout:2,displayMode:"once",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",position:"topRight"})}}function y(t){const e=t.map(o=>`<li class="gallery-item">
        <a class="gallery-link" href="${o.largeImageURL}">
            <img
                width=360;
                height=200;
                class="gallery-image"
                src="${o.webformatURL}"
                alt="${o.tags} " />
        </a>
                <div class="image-info">
                <p class = "info-item"><strong>LIKES:</strong> ${o.likes}</p>
                <p class = "info-item"><strong>VIEWS:</strong> ${o.views}</p>
                <p class = "info-item"><strong>COMMENTS:</strong> ${o.comments}</p>
                <p class = "info-item"><strong>DOWNLOADS: </strong>${o.downloads}</p>
                </div>
        </li>
        `).join("");s.imgGallery.insertAdjacentHTML("beforeend",e),lightbox.refresh()}function f(){s.formSearch.reset()}function L(){s.loader.classList.remove("hidden")}function u(){s.loader.classList.add("hidden")}function S(){s.moreBtn.style.display="flex"}function m(){s.loader.classList.add("hidden")}function M(t,e){t>=e?(m(),e&&n.info({title:"The end!",message:"We're sorry, but you've reached the end of search results."})):S()}function v(t=0,e=0){const a=s.imgGallery.children[0].getBoundingClientRect().height;window.scrollBy({top:a*2,left:e,behavior:"smooth"})}let c="",l=1,g=1;const p=15,s={formSearch:document.querySelector(".form"),inputImgSearch:document.querySelector(".input-search"),imgGallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),moreBtn:document.querySelector(".more-button")},b=new w(".gallery a",{captionsData:"alt",captionDelay:250});s.formSearch.addEventListener("submit",async t=>{if(t.preventDefault(),l=1,c=s.inputImgSearch.value.trim(),m(),c===""){s.imgGallery.innerHTML=" ",n.warning({title:"warning",message:" Enter a word for the query, please.",layout:2,position:"topRight",displayMode:"once",color:"#ef4000",messageColor:"#fff",messageSize:"16"}),f();return}L(),s.imgGallery.innerHTML=" ";try{const e=await h(c,l,p);if(g=Math.ceil(e.totalHits/p),g===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",displayMode:"once",color:"#ef4040",messageColor:"#fff",messageSize:"16",layout:2}),f(),u();return}u(),f(),y(e.hits),b.refresh(),S()}catch(e){n.error({title:"Error",message:`${e}`,layout:2,displayMode:"once",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",position:"topRight"})}});s.moreBtn.addEventListener("click",async()=>{l++,m(),L();try{const t=await h(c,l,p);t.hits.length!==0&&(y(t.hits),b.refresh(),u()),M(l,g),v()}catch(t){n.error({title:"Error",message:`${t}`,layout:2,displayMode:"once",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",position:"topRight"})}});
//# sourceMappingURL=commonHelpers.js.map
