import{a as B,i as n,S as w}from"./assets/vendor-f144e563.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const i of r)if(i.type==="childList")for(const f of i.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&a(f)}).observe(document,{childList:!0,subtree:!0});function o(r){const i={};return r.integrity&&(i.integrity=r.integrity),r.referrerPolicy&&(i.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?i.credentials="include":r.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function a(r){if(r.ep)return;r.ep=!0;const i=o(r);fetch(r.href,i)}})();const E=B.create({baseURL:"https://pixabay.com"});async function p(t,e,o){try{return(await E.get("/api/",{params:{key:"44578932-6e2bdfbc9295001d2a495ef0a",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:o,page:e}})).data}catch(a){n.error({title:"Error",message:`${a}`,layout:2,displayMode:"once",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",position:"topRight"})}}function h(t){const e=t.map(o=>`<li class="gallery-item">
        <a class="gallery-link" href="${o.largeImageURL}">
            <img
                width=360;
                height=200;
                class="gallery-image"
                src="${o.webformatURL}"
                alt="${o.tags} " />
        </a>
                <div class="image-info">
                <p class = "info-item"><strong>LIKES:</strong> ${o.likes}</p>
                <p class = "info-item"><strong>VIEWS:</strong> ${o.views}</p>
                <p class = "info-item"><strong>COMMENTS:</strong> ${o.comments}</p>
                <p class = "info-item"><strong>DOWNLOADS: </strong>${o.downloads}</p>
                </div>
        </li>
        `).join("");s.imgGallery.insertAdjacentHTML("beforeend",e)}function m(){s.formSearch.reset()}function y(){s.loader.classList.remove("hidden")}function L(){s.loader.classList.add("hidden")}function S(){s.moreBtn.classList.remove("more-hidden")}function d(){s.moreBtn.classList.add("more-hidden")}function M(t,e){t>=e?(d(),n.info({title:"The end!",message:"We're sorry, but you've reached the end of search results."})):S()}function v(t=0,e=0){const a=s.imgGallery.children[0].getBoundingClientRect().height;window.scrollBy({top:a*2,left:e,behavior:"smooth"})}let c="",l=1,u=1;const g=15,s={formSearch:document.querySelector(".form"),inputImgSearch:document.querySelector(".input-search"),imgGallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),moreBtn:document.querySelector(".more-button")},b=new w(".gallery a",{captionsData:"alt",captionDelay:250});s.formSearch.addEventListener("submit",async t=>{if(t.preventDefault(),l=1,c=s.inputImgSearch.value.trim(),c===""){s.imgGallery.innerHTML=" ",n.warning({title:"warning",message:" Enter a word for the query, please.",layout:2,position:"topRight",displayMode:"once",color:"#ef4000",messageColor:"#fff",messageSize:"16"}),d(),m();return}y(),s.imgGallery.innerHTML=" ";try{const e=await p(c,l,g);if(u=Math.ceil(e.totalHits/g),u===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",displayMode:"once",color:"#ef4040",messageColor:"#fff",messageSize:"16",layout:2});return}m(),h(e.hits),b.refresh(),L(),S()}catch(e){n.error({title:"Error",message:`${e}`,layout:2,displayMode:"once",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",position:"topRight"})}});s.moreBtn.addEventListener("click",async()=>{try{y(),d(),l++;const t=await p(c,l,g);t.hits.length!==0&&(h(t.hits),b.refresh()),v(),M(l,u),L()}catch(t){d(),n.error({title:"Error",message:`${t}`,layout:2,displayMode:"once",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",position:"topRight"})}});
//# sourceMappingURL=commonHelpers.js.map
